package com.coding91.ui;

import com.coding91.parser.ConfigParserDispatch;
import com.coding91.utils.FileUtils;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class DessertShopConfigParseJFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form TotemConfigParseJFrame
     */
    public DessertShopConfigParseJFrame() {
        Map<String, String> configMap = FileUtils.loadSetting("resources/data/setting.properties");
        configBaseDir = configMap.get("configBaseDir");
        outputDirectory = configMap.get("outputDirectory");
        initFuncMap();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        funcbuttonGroup = new javax.swing.ButtonGroup();
        langjbuttonGroup = new javax.swing.ButtonGroup();
        jLayeredPane = new javax.swing.JLayeredPane();
        funjPanel = new javax.swing.JPanel();
        shopObjItemjRadioButton = new javax.swing.JRadioButton();
        activityLibraryjRadioButton = new javax.swing.JRadioButton();
        avatarItemsjRadioButton = new javax.swing.JRadioButton();
        bindingRecipejRadioButton = new javax.swing.JRadioButton();
        feedInfojRadioButton = new javax.swing.JRadioButton();
        goodsOrderjRadioButton = new javax.swing.JRadioButton();
        requestInfojRadioButton = new javax.swing.JRadioButton();
        gamejRadioButton = new javax.swing.JRadioButton();
        missionInfojRadioButton = new javax.swing.JRadioButton();
        dessertInfojRadioButton = new javax.swing.JRadioButton();
        giftPackagejRadioButton = new javax.swing.JRadioButton();
        objItemjRadioButton = new javax.swing.JRadioButton();
        allInOneYesjRadioButton = new javax.swing.JRadioButton();
        selectConfgFilejPanel = new javax.swing.JPanel();
        configFilejLabel = new javax.swing.JLabel();
        configFilejTextField = new javax.swing.JTextField();
        configFilejButton = new javax.swing.JButton();
        outputjLabel = new javax.swing.JLabel();
        outputjTextField = new javax.swing.JTextField();
        outputjButton = new javax.swing.JButton();
        operationjPanel = new javax.swing.JPanel();
        parsejButton = new javax.swing.JButton();
        closejButton = new javax.swing.JButton();
        dsParseConfjToolBar = new javax.swing.JToolBar();
        allInOnejPanel = new javax.swing.JPanel();
        langEnUsjCheckBox = new javax.swing.JCheckBox();
        langFrFrjCheckBox = new javax.swing.JCheckBox();
        langDeDejCheckBox = new javax.swing.JCheckBox();
        langEsEsjCheckBox = new javax.swing.JCheckBox();
        langZhTwjCheckBox = new javax.swing.JCheckBox();
        langItItjCheckBox = new javax.swing.JCheckBox();
        selectAlljRadioButton = new javax.swing.JRadioButton();
        selectRevertjRadioButton = new javax.swing.JRadioButton();
        selectNonejRadioButton = new javax.swing.JRadioButton();
        bottomStatusjLabel = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        filejMenu = new javax.swing.JMenu();
        settingjMenuItem = new javax.swing.JMenuItem();
        editjMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        funjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("解析内容"));

        funcbuttonGroup.add(shopObjItemjRadioButton);
        shopObjItemjRadioButton.setText("shopItem");
        shopObjItemjRadioButton.setActionCommand("SHOP_ITEM");
        shopObjItemjRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shopObjItemjRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(activityLibraryjRadioButton);
        activityLibraryjRadioButton.setText("activityLibraryInfo");
        activityLibraryjRadioButton.setActionCommand("ACTIVITY_LIB");
        activityLibraryjRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                activityLibraryjRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(avatarItemsjRadioButton);
        avatarItemsjRadioButton.setText("avatarItems");
        avatarItemsjRadioButton.setActionCommand("AVATAR_ITEMS");
        avatarItemsjRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avatarItemsjRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(bindingRecipejRadioButton);
        bindingRecipejRadioButton.setText("bindingRecipe");
        bindingRecipejRadioButton.setActionCommand("BINDING_RECIPE");
        bindingRecipejRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bindingRecipejRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(feedInfojRadioButton);
        feedInfojRadioButton.setText("feedInfo");
        feedInfojRadioButton.setActionCommand("FEED_INFO");
        feedInfojRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedInfojRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(goodsOrderjRadioButton);
        goodsOrderjRadioButton.setText("goodsOrder");
        goodsOrderjRadioButton.setActionCommand("GOODS_ORDER");
        goodsOrderjRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goodsOrderjRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(requestInfojRadioButton);
        requestInfojRadioButton.setText("requestInfo");
        requestInfojRadioButton.setActionCommand("REQUEST_INFO");
        requestInfojRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestInfojRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(gamejRadioButton);
        gamejRadioButton.setText("game");
        gamejRadioButton.setActionCommand("GAME");
        gamejRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gamejRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(missionInfojRadioButton);
        missionInfojRadioButton.setText("missionInfo");
        missionInfojRadioButton.setActionCommand("MISSION_INFO");
        missionInfojRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                missionInfojRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(dessertInfojRadioButton);
        dessertInfojRadioButton.setText("dessertInfo");
        dessertInfojRadioButton.setActionCommand("DESSERT_INFO");
        dessertInfojRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dessertInfojRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(giftPackagejRadioButton);
        giftPackagejRadioButton.setText("giftPackage");
        giftPackagejRadioButton.setActionCommand("GIFT_PACKAGE");
        giftPackagejRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                giftPackagejRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(objItemjRadioButton);
        objItemjRadioButton.setText("objItem");
        objItemjRadioButton.setActionCommand("OBJ_ITEM");
        objItemjRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                objItemjRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(allInOneYesjRadioButton);
        allInOneYesjRadioButton.setSelected(true);
        allInOneYesjRadioButton.setText("parse ALL");
        allInOneYesjRadioButton.setActionCommand("YES");
        allInOneYesjRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allInOneYesjRadioButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout funjPanelLayout = new javax.swing.GroupLayout(funjPanel);
        funjPanel.setLayout(funjPanelLayout);
        funjPanelLayout.setHorizontalGroup(
            funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(funjPanelLayout.createSequentialGroup()
                .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bindingRecipejRadioButton)
                    .addComponent(shopObjItemjRadioButton)
                    .addComponent(giftPackagejRadioButton)
                    .addComponent(allInOneYesjRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(feedInfojRadioButton)
                    .addComponent(activityLibraryjRadioButton)
                    .addComponent(dessertInfojRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(missionInfojRadioButton)
                    .addComponent(avatarItemsjRadioButton)
                    .addComponent(requestInfojRadioButton))
                .addGap(27, 27, 27)
                .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gamejRadioButton)
                    .addComponent(goodsOrderjRadioButton)
                    .addComponent(objItemjRadioButton))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        funjPanelLayout.setVerticalGroup(
            funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(funjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activityLibraryjRadioButton)
                    .addComponent(avatarItemsjRadioButton)
                    .addComponent(goodsOrderjRadioButton)
                    .addComponent(allInOneYesjRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bindingRecipejRadioButton)
                    .addComponent(feedInfojRadioButton)
                    .addComponent(requestInfojRadioButton)
                    .addComponent(gamejRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(missionInfojRadioButton)
                    .addComponent(dessertInfojRadioButton)
                    .addComponent(giftPackagejRadioButton)
                    .addComponent(objItemjRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shopObjItemjRadioButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLayeredPane.add(funjPanel);
        funjPanel.setBounds(10, 0, 520, 160);

        selectConfgFilejPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("选择配置文件"));

        configFilejLabel.setText("配置文件：");

        configFilejTextField.setText(configBaseDir);
        configFilejTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configFilejTextFieldMouseClicked(evt);
            }
        });

        configFilejButton.setText("浏览");
        configFilejButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configFilejButtonMouseClicked(evt);
            }
        });

        outputjLabel.setText("输出目录：");

        outputjTextField.setText(outputDirectory);
        outputjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outputjTextFieldMouseClicked(evt);
            }
        });

        outputjButton.setText("浏览");
        outputjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outputjButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout selectConfgFilejPanelLayout = new javax.swing.GroupLayout(selectConfgFilejPanel);
        selectConfgFilejPanel.setLayout(selectConfgFilejPanelLayout);
        selectConfgFilejPanelLayout.setHorizontalGroup(
            selectConfgFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectConfgFilejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectConfgFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outputjLabel)
                    .addComponent(configFilejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selectConfgFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(configFilejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(outputjTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selectConfgFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(configFilejButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outputjButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(78, 78, 78))
        );
        selectConfgFilejPanelLayout.setVerticalGroup(
            selectConfgFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectConfgFilejPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(selectConfgFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(configFilejLabel)
                    .addComponent(configFilejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(configFilejButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selectConfgFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputjLabel)
                    .addComponent(outputjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputjButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane.add(selectConfgFilejPanel);
        selectConfgFilejPanel.setBounds(0, 260, 520, 80);

        operationjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("操作"));

        parsejButton.setText("解析");
        parsejButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parsejButtonMouseClicked(evt);
            }
        });

        closejButton.setText("取消");
        closejButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closejButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout operationjPanelLayout = new javax.swing.GroupLayout(operationjPanel);
        operationjPanel.setLayout(operationjPanelLayout);
        operationjPanelLayout.setHorizontalGroup(
            operationjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationjPanelLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(parsejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(closejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        operationjPanelLayout.setVerticalGroup(
            operationjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(operationjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parsejButton)
                    .addComponent(closejButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane.add(operationjPanel);
        operationjPanel.setBounds(0, 350, 520, 67);

        dsParseConfjToolBar.setRollover(true);
        dsParseConfjToolBar.setMaximumSize(new java.awt.Dimension(520, 22));
        dsParseConfjToolBar.setMinimumSize(new java.awt.Dimension(520, 22));
        jLayeredPane.add(dsParseConfjToolBar);
        dsParseConfjToolBar.setBounds(0, 420, 530, 20);

        allInOnejPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("需要转换的语言"));

        langEnUsjCheckBox.setSelected(true);
        langEnUsjCheckBox.setText("en_us");
        langEnUsjCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                langEnUsjCheckBoxMouseClicked(evt);
            }
        });

        langFrFrjCheckBox.setSelected(true);
        langFrFrjCheckBox.setText("fr_fr");
        langFrFrjCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                langFrFrjCheckBoxMouseClicked(evt);
            }
        });

        langDeDejCheckBox.setSelected(true);
        langDeDejCheckBox.setText("de_de");
        langDeDejCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                langDeDejCheckBoxMouseClicked(evt);
            }
        });

        langEsEsjCheckBox.setSelected(true);
        langEsEsjCheckBox.setText("es_es");
        langEsEsjCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                langEsEsjCheckBoxMouseClicked(evt);
            }
        });

        langZhTwjCheckBox.setSelected(true);
        langZhTwjCheckBox.setText("zh_tw");
        langZhTwjCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                langZhTwjCheckBoxMouseClicked(evt);
            }
        });

        langItItjCheckBox.setSelected(true);
        langItItjCheckBox.setText("it_it");
        langItItjCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                langItItjCheckBoxMouseClicked(evt);
            }
        });

        langjbuttonGroup.add(selectAlljRadioButton);
        selectAlljRadioButton.setSelected(true);
        selectAlljRadioButton.setText("全选");
        selectAlljRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectAlljRadioButtonMouseClicked(evt);
            }
        });

        langjbuttonGroup.add(selectRevertjRadioButton);
        selectRevertjRadioButton.setText("反选");
        selectRevertjRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectRevertjRadioButtonMouseClicked(evt);
            }
        });

        langjbuttonGroup.add(selectNonejRadioButton);
        selectNonejRadioButton.setText("全不选");
        selectNonejRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectNonejRadioButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout allInOnejPanelLayout = new javax.swing.GroupLayout(allInOnejPanel);
        allInOnejPanel.setLayout(allInOnejPanelLayout);
        allInOnejPanelLayout.setHorizontalGroup(
            allInOnejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allInOnejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(allInOnejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(langEnUsjCheckBox)
                    .addComponent(selectAlljRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(allInOnejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(allInOnejPanelLayout.createSequentialGroup()
                        .addComponent(langDeDejCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(langFrFrjCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(langEsEsjCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(langZhTwjCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(langItItjCheckBox))
                    .addGroup(allInOnejPanelLayout.createSequentialGroup()
                        .addComponent(selectRevertjRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectNonejRadioButton)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        allInOnejPanelLayout.setVerticalGroup(
            allInOnejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allInOnejPanelLayout.createSequentialGroup()
                .addGroup(allInOnejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(langEnUsjCheckBox)
                    .addComponent(langFrFrjCheckBox)
                    .addComponent(langDeDejCheckBox)
                    .addComponent(langEsEsjCheckBox)
                    .addComponent(langItItjCheckBox)
                    .addComponent(langZhTwjCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addGroup(allInOnejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectAlljRadioButton)
                    .addComponent(selectRevertjRadioButton)
                    .addComponent(selectNonejRadioButton))
                .addContainerGap())
        );

        jLayeredPane.add(allInOnejPanel);
        allInOnejPanel.setBounds(10, 160, 520, 80);

        bottomStatusjLabel.setFocusable(false);
        bottomStatusjLabel.setMaximumSize(new java.awt.Dimension(520, 20));
        bottomStatusjLabel.setMinimumSize(new java.awt.Dimension(520, 20));
        bottomStatusjLabel.setName(""); // NOI18N
        jLayeredPane.add(bottomStatusjLabel);
        bottomStatusjLabel.setBounds(10, 430, 517, 18);

        filejMenu.setText("文件");

        settingjMenuItem.setText("设置");
        settingjMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingjMenuItemMouseClicked(evt);
            }
        });
        settingjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingjMenuItemActionPerformed(evt);
            }
        });
        filejMenu.add(settingjMenuItem);

        jMenuBar.add(filejMenu);

        editjMenu.setText("编辑");
        jMenuBar.add(editjMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static List<String> langList;
    public static final int LANG_COUNT_MIX = 0;
    public static final int LANG_COUNT_MAX = 6;
    private static int selectedCheckboxCount = LANG_COUNT_MAX;

    private void initLangList() {
        if (null == langList) {
            langList = new ArrayList<>();
            if (langEnUsjCheckBox.isSelected()) {
                langList.add("en_us");
            }
            if (langDeDejCheckBox.isSelected()) {
                langList.add("de_de");
            }
            if (langFrFrjCheckBox.isSelected()) {
                langList.add("fr_fr");
            }
            if (langEsEsjCheckBox.isSelected()) {
                langList.add("es_es");
            }
            if (langZhTwjCheckBox.isSelected()) {
                langList.add("zh_tw");
            }
            if (langItItjCheckBox.isSelected()) {
                langList.add("it_it");
            }
        }
    }

    public static List<String> getLangList() {
        return DessertShopConfigParseJFrame.langList;
    }

    private void changeFunctionButtonStatus() {
        langjbuttonGroup.clearSelection();
        if (selectedCheckboxCount == 0) {
            selectNonejRadioButton.setSelected(true);
        } else if (selectedCheckboxCount == LANG_COUNT_MAX) {
            selectAlljRadioButton.setSelected(true);
        }
    }

    private int calcCheckBoxCount(int offset) {
        selectedCheckboxCount += offset;
        if (selectedCheckboxCount <= 0) {
            selectedCheckboxCount = 0;
        } else if (selectedCheckboxCount >= LANG_COUNT_MAX) {
            selectedCheckboxCount = LANG_COUNT_MAX;
        }
        return selectedCheckboxCount;
    }

    private int calcCheckBoxCount() {
        selectedCheckboxCount = 0;
        if (langEnUsjCheckBox.isSelected()) {
            selectedCheckboxCount += 1;
        }
        if (langDeDejCheckBox.isSelected()) {
            selectedCheckboxCount += 1;
        }
        if (langFrFrjCheckBox.isSelected()) {
            selectedCheckboxCount += 1;
        }
        if (langEsEsjCheckBox.isSelected()) {
            selectedCheckboxCount += 1;
        }
        if (langZhTwjCheckBox.isSelected()) {
            selectedCheckboxCount += 1;
        }
        if (langItItjCheckBox.isSelected()) {
            selectedCheckboxCount += 1;
        }

        return selectedCheckboxCount;
    }


    private void parsejButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parsejButtonMouseClicked
//        long startTime = System.currentTimeMillis();
        if (selectedCheckboxCount == 0) {
            JOptionPane.showMessageDialog(null, "至少要选择一个语言", "信息提示", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String function = "";
        if (funcbuttonGroup.getSelection() != null) {
            function = funcbuttonGroup.getSelection().getActionCommand();
        }

        ControllerJFrame.showNoticeMessageJFrame();
        
        NoticeMessageJFrame.noticeMessage("开始转换,请耐心等待。。。。");
        
        String msg = null;
        if ("YES".equals(function)) {//全部转换
            //配置文件
            String configFilePath = configFilejTextField.getText();
            //输出路径
            String outputPath = outputjTextField.getText();
            initLangList();
            funcMap.entrySet().stream().forEach((entry) -> {
                String currentFunction = entry.getKey();
                String excelFileName = entry.getValue();
                ConfigParserDispatch.transformSingleExcel(currentFunction, configFilePath + "/" + excelFileName, outputPath);
            });
        } else {//转换某一个配置项
            //配置文件
            String configFilePath = configFilejTextField.getText();
            //输出路径
            String outputPath = outputjTextField.getText();

            if (function.isEmpty()) {
                msg = "请选择解析内容 ";
            } else if (configFilePath.isEmpty()) {
                msg = "请选择待解析文件(xls) ";
            } else if (outputPath.isEmpty()) {
                msg = "请选择输出路径";
            }
            if (msg != null && !msg.isEmpty()) {
                JOptionPane.showMessageDialog(null, msg, "信息提示", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
            initLangList();
            ConfigParserDispatch.transformSingleExcel(function, configFilePath, outputPath);
        }
    }//GEN-LAST:event_parsejButtonMouseClicked

    private static Map<String, String> funcMap;

    private Map<String, String> initFuncMap() {
        if (null == funcMap) {
            funcMap = new HashMap();
            funcMap.put("SHOP_ITEM", "shopItem.xls");
            funcMap.put("ACTIVITY_LIB", "activityLibraryInfo.xls");
            funcMap.put("AVATAR_ITEMS", "avatarItems.xls");
            funcMap.put("GOODS_ORDER", "goodsOrder.xls");
            funcMap.put("BINDING_RECIPE", "bindingRecipe.xls");
            funcMap.put("FEED_INFO", "feedInfo.xls");
            funcMap.put("REQUEST_INFO", "requestInfo.xls");
            funcMap.put("GAME", "game.xls");
            funcMap.put("GIFT_PACKAGE", "giftPackage.xls");
            funcMap.put("DESSERT_INFO", "dessertInfo.xls");
            funcMap.put("MISSION_INFO", "missionInfo.xls");
            funcMap.put("OBJ_ITEM", "objItem.xls");
        }

        return funcMap;
    }

    public static String getLineInfo() {
        StackTraceElement ste = new Throwable().getStackTrace()[1];
        return ste.getFileName() + ": Line " + ste.getLineNumber();
    }

    public static void showErrorMsg(String msg, String title) {
        showErrorMsg(msg, title, true);
    }

    public static void showErrorMsg(String msg, String title, boolean needExit) {
        JOptionPane.showMessageDialog(null, msg, title, JOptionPane.ERROR_MESSAGE, null);
        if (needExit) {
            System.exit(0);
        }
    }

    public static void showErrorMsgWithoutExit(String msg, String title) {
        showErrorMsg(msg, title, false);
    }

    public void transformFinish(String message) {
        JOptionPane.showMessageDialog(null, message);
        ControllerJFrame.dispose();
    }

    private void closejButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closejButtonMouseClicked
        ControllerJFrame.dispose();
    }//GEN-LAST:event_closejButtonMouseClicked

    private void settingjMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingjMenuItemMouseClicked
    }//GEN-LAST:event_settingjMenuItemMouseClicked

    private void outputjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outputjButtonMouseClicked
        this.outputjTextFieldMouseClicked(evt);
    }//GEN-LAST:event_outputjButtonMouseClicked

    private void outputjTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outputjTextFieldMouseClicked
        File f = new File(outputDirectory);
        JFileChooser jfc = new JFileChooser(f);
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result;
        result = jfc.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = jfc.getSelectedFile();
            outputjTextField.setText(file.getPath());
        }
    }//GEN-LAST:event_outputjTextFieldMouseClicked

    private void configFilejButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configFilejButtonMouseClicked
        this.configFilejTextFieldMouseClicked(evt);
    }//GEN-LAST:event_configFilejButtonMouseClicked

    private void configFilejTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configFilejTextFieldMouseClicked
        File f = new File(configBaseDir);
        JFileChooser jfc = new JFileChooser(f);
        //        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result;
        result = jfc.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = jfc.getSelectedFile();
            configFilejTextField.setText(file.getPath());
        }
    }//GEN-LAST:event_configFilejTextFieldMouseClicked

    private void settingjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingjMenuItemActionPerformed
        NoticeMessageJFrame.showMessageDialogMessage("edit");
    }//GEN-LAST:event_settingjMenuItemActionPerformed

    private void selectNonejRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectNonejRadioButtonMouseClicked
        langEnUsjCheckBox.setSelected(false);
        langDeDejCheckBox.setSelected(false);
        langFrFrjCheckBox.setSelected(false);
        langEsEsjCheckBox.setSelected(false);
        langZhTwjCheckBox.setSelected(false);
        langItItjCheckBox.setSelected(false);
        calcCheckBoxCount(-LANG_COUNT_MAX);
    }//GEN-LAST:event_selectNonejRadioButtonMouseClicked

    /**
     * 反选
     *
     * @param evt
     */
    private void selectRevertjRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectRevertjRadioButtonMouseClicked
        langEnUsjCheckBox.setSelected(!langEnUsjCheckBox.isSelected());
        langDeDejCheckBox.setSelected(!langDeDejCheckBox.isSelected());
        langFrFrjCheckBox.setSelected(!langFrFrjCheckBox.isSelected());
        langEsEsjCheckBox.setSelected(!langEsEsjCheckBox.isSelected());
        langZhTwjCheckBox.setSelected(!langZhTwjCheckBox.isSelected());
        langItItjCheckBox.setSelected(!langItItjCheckBox.isSelected());
        calcCheckBoxCount(LANG_COUNT_MAX - 2 * selectedCheckboxCount);
    }//GEN-LAST:event_selectRevertjRadioButtonMouseClicked

    /**
     * 全选
     *
     * @param evt
     */
    private void selectAlljRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectAlljRadioButtonMouseClicked
        langEnUsjCheckBox.setSelected(true);
        langDeDejCheckBox.setSelected(true);
        langFrFrjCheckBox.setSelected(true);
        langEsEsjCheckBox.setSelected(true);
        langZhTwjCheckBox.setSelected(true);
        langItItjCheckBox.setSelected(true);
        calcCheckBoxCount(LANG_COUNT_MAX);
    }//GEN-LAST:event_selectAlljRadioButtonMouseClicked

    private void langEnUsjCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_langEnUsjCheckBoxMouseClicked
        langCheckBoxClicked(evt);
    }//GEN-LAST:event_langEnUsjCheckBoxMouseClicked

    private void langDeDejCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_langDeDejCheckBoxMouseClicked
        langCheckBoxClicked(evt);
    }//GEN-LAST:event_langDeDejCheckBoxMouseClicked

    private void langFrFrjCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_langFrFrjCheckBoxMouseClicked
        langCheckBoxClicked(evt);
    }//GEN-LAST:event_langFrFrjCheckBoxMouseClicked

    private void langEsEsjCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_langEsEsjCheckBoxMouseClicked
        langCheckBoxClicked(evt);
    }//GEN-LAST:event_langEsEsjCheckBoxMouseClicked

    private void langZhTwjCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_langZhTwjCheckBoxMouseClicked
        langCheckBoxClicked(evt);
    }//GEN-LAST:event_langZhTwjCheckBoxMouseClicked

    private void langItItjCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_langItItjCheckBoxMouseClicked
        langCheckBoxClicked(evt);
    }//GEN-LAST:event_langItItjCheckBoxMouseClicked

    private void allInOneYesjRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allInOneYesjRadioButtonMouseClicked
        setConfigFilejTextField(evt);
    }//GEN-LAST:event_allInOneYesjRadioButtonMouseClicked

    private void activityLibraryjRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activityLibraryjRadioButtonMouseClicked
        setConfigFilejTextField(evt);
    }//GEN-LAST:event_activityLibraryjRadioButtonMouseClicked

    private void avatarItemsjRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avatarItemsjRadioButtonMouseClicked
        setConfigFilejTextField(evt);
    }//GEN-LAST:event_avatarItemsjRadioButtonMouseClicked

    private void goodsOrderjRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goodsOrderjRadioButtonMouseClicked
        setConfigFilejTextField(evt);
    }//GEN-LAST:event_goodsOrderjRadioButtonMouseClicked

    private void bindingRecipejRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bindingRecipejRadioButtonMouseClicked
        setConfigFilejTextField(evt);
    }//GEN-LAST:event_bindingRecipejRadioButtonMouseClicked

    private void feedInfojRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedInfojRadioButtonMouseClicked
        setConfigFilejTextField(evt);
    }//GEN-LAST:event_feedInfojRadioButtonMouseClicked

    private void requestInfojRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestInfojRadioButtonMouseClicked
        setConfigFilejTextField(evt);
    }//GEN-LAST:event_requestInfojRadioButtonMouseClicked

    private void gamejRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gamejRadioButtonMouseClicked
        setConfigFilejTextField(evt);
    }//GEN-LAST:event_gamejRadioButtonMouseClicked

    private void giftPackagejRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_giftPackagejRadioButtonMouseClicked
        setConfigFilejTextField(evt);
    }//GEN-LAST:event_giftPackagejRadioButtonMouseClicked

    private void dessertInfojRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dessertInfojRadioButtonMouseClicked
        setConfigFilejTextField(evt);
    }//GEN-LAST:event_dessertInfojRadioButtonMouseClicked

    private void missionInfojRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_missionInfojRadioButtonMouseClicked
        setConfigFilejTextField(evt);
    }//GEN-LAST:event_missionInfojRadioButtonMouseClicked

    private void objItemjRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_objItemjRadioButtonMouseClicked
        setConfigFilejTextField(evt);
    }//GEN-LAST:event_objItemjRadioButtonMouseClicked

    private void shopObjItemjRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shopObjItemjRadioButtonMouseClicked
        setConfigFilejTextField(evt);
    }//GEN-LAST:event_shopObjItemjRadioButtonMouseClicked

    private void setConfigFilejTextField(java.awt.event.MouseEvent evt) {
        javax.swing.JRadioButton currentJradioButton = (javax.swing.JRadioButton) evt.getSource();
        String cmd = currentJradioButton.getActionCommand();
        if (funcMap.containsKey(cmd)) {
            configFilejTextField.setText(configBaseDir + "\\" + funcMap.get(cmd));
        } else {
            configFilejTextField.setText(configBaseDir);
        }
    }

    private void langCheckBoxClicked(java.awt.event.MouseEvent evt) {
        javax.swing.JCheckBox currentCheckBox = (javax.swing.JCheckBox) evt.getSource();
        if (currentCheckBox.isSelected()) {
            calcCheckBoxCount(1);
        } else {
            calcCheckBoxCount(-1);
        }
        changeFunctionButtonStatus();
    }

    private static void showMessageDialogMessage(Exception ex) {
        String exMsg = ex.toString();
        JOptionPane.showMessageDialog(null, exMsg + new Throwable().getStackTrace()[1].toString(), "错误信息提示", JOptionPane.ERROR_MESSAGE);
    }

    private final String configBaseDir;
    private final String outputDirectory;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activityLibraryjRadioButton;
    private javax.swing.JRadioButton allInOneYesjRadioButton;
    private javax.swing.JPanel allInOnejPanel;
    private javax.swing.JRadioButton avatarItemsjRadioButton;
    private javax.swing.JRadioButton bindingRecipejRadioButton;
    private javax.swing.JLabel bottomStatusjLabel;
    private javax.swing.JButton closejButton;
    private javax.swing.JButton configFilejButton;
    private javax.swing.JLabel configFilejLabel;
    private javax.swing.JTextField configFilejTextField;
    private javax.swing.JRadioButton dessertInfojRadioButton;
    private javax.swing.JToolBar dsParseConfjToolBar;
    private javax.swing.JMenu editjMenu;
    private javax.swing.JRadioButton feedInfojRadioButton;
    private javax.swing.JMenu filejMenu;
    private javax.swing.ButtonGroup funcbuttonGroup;
    private javax.swing.JPanel funjPanel;
    private javax.swing.JRadioButton gamejRadioButton;
    private javax.swing.JRadioButton giftPackagejRadioButton;
    private javax.swing.JRadioButton goodsOrderjRadioButton;
    private javax.swing.JLayeredPane jLayeredPane;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JCheckBox langDeDejCheckBox;
    private javax.swing.JCheckBox langEnUsjCheckBox;
    private javax.swing.JCheckBox langEsEsjCheckBox;
    private javax.swing.JCheckBox langFrFrjCheckBox;
    private javax.swing.JCheckBox langItItjCheckBox;
    private javax.swing.JCheckBox langZhTwjCheckBox;
    private javax.swing.ButtonGroup langjbuttonGroup;
    private javax.swing.JRadioButton missionInfojRadioButton;
    private javax.swing.JRadioButton objItemjRadioButton;
    private javax.swing.JPanel operationjPanel;
    private javax.swing.JButton outputjButton;
    private javax.swing.JLabel outputjLabel;
    private javax.swing.JTextField outputjTextField;
    private javax.swing.JButton parsejButton;
    private javax.swing.JRadioButton requestInfojRadioButton;
    private javax.swing.JRadioButton selectAlljRadioButton;
    private javax.swing.JPanel selectConfgFilejPanel;
    private javax.swing.JRadioButton selectNonejRadioButton;
    private javax.swing.JRadioButton selectRevertjRadioButton;
    private javax.swing.JMenuItem settingjMenuItem;
    private javax.swing.JRadioButton shopObjItemjRadioButton;
    // End of variables declaration//GEN-END:variables
}
